version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "5002:5001"
